<#
.SYNOPSIS
    Universal winget package updater that works for ANY application.

.DESCRIPTION
    This script generates Intune proactive remediation scripts for any winget package:
    - Detects if updates are available
    - Checks if app is running (prevents forced closure)
    - Installs updates silently
    - Works in SYSTEM context
    - Generates both detect.ps1 and remediate.ps1
    - Supports batch creation for multiple apps

.PARAMETER AppName
    Display name of the application (used for reporting).

.PARAMETER WingetID
    The winget package ID (e.g., 'Google.Chrome', 'Microsoft.PowerToys').

.PARAMETER ProcessName
    The process name to check if app is running (without .exe).

.PARAMETER OutputPath
    Where to save the generated scripts (default: current directory).

.PARAMETER ForceUpdate
    Update even if the app is running.

.PARAMETER GenerateBatch
    Generate scripts for multiple apps from a CSV file.

.PARAMETER CSVPath
    Path to CSV file with columns: AppName,WingetID,ProcessName

.EXAMPLE
    .\New-BulkWingetUpdater.ps1 -AppName "Google Chrome" -WingetID "Google.Chrome" -ProcessName "chrome"
    Generates detect.ps1 and remediate.ps1 for Chrome updates.

.EXAMPLE
    .\New-BulkWingetUpdater.ps1 -GenerateBatch -CSVPath ".\apps.csv"
    Generates remediation scripts for all apps in the CSV.

.EXAMPLE
    # CSV format:
    # AppName,WingetID,ProcessName
    # Google Chrome,Google.Chrome,chrome
    # 7-Zip,7zip.7zip,7zFM
    # Microsoft Teams,Microsoft.Teams,Teams

.NOTES
    Requires winget to be installed on target devices
    Compatible with Windows 10/11
    Designed for Intune Proactive Remediations
#>

[CmdletBinding(DefaultParameterSetName='Single')]
param(
    [Parameter(Mandatory=$true, ParameterSetName='Single')]
    [string]$AppName,

    [Parameter(Mandatory=$true, ParameterSetName='Single')]
    [string]$WingetID,

    [Parameter(Mandatory=$true, ParameterSetName='Single')]
    [string]$ProcessName,

    [Parameter(Mandatory=$false)]
    [string]$OutputPath = ".",

    [Parameter(Mandatory=$false, ParameterSetName='Single')]
    [switch]$ForceUpdate,

    [Parameter(Mandatory=$true, ParameterSetName='Batch')]
    [switch]$GenerateBatch,

    [Parameter(Mandatory=$true, ParameterSetName='Batch')]
    [string]$CSVPath
)

function Write-ColorOutput {
    param([string]$Message, [string]$Level = 'Info')
    $color = switch($Level) {
        'Success' { 'Green' }
        'Warning' { 'Yellow' }
        'Error' { 'Red' }
        default { 'Cyan' }
    }
    Write-Host $Message -ForegroundColor $color
}

function New-DetectScript {
    param(
        [string]$Name,
        [string]$ID,
        [string]$Process,
        [bool]$Force = $false
    )

    $processCheck = if(-not $Force) {
@"
try {
`$process = Get-Process -Name "$Process" -ErrorAction SilentlyContinue
# Check if there's an available update
if ((`$lines -match '\bVersion\s+Available\b' -and `$process -ne `$null)) {
    `$verInstalled, `$verAvailable = (-split `$lines[-1])[-3,-2]
    Write-Host "Application update available for $Name. Current version is `$verInstalled, version available is `$verAvailable. $Name is currently running, will try again later."
    [PSCustomObject]@{
        Name = "$Name"
        InstalledVersion = `$verInstalled
        AvailableVersion = `$verAvailable
        Status = "Running"
    }
    exit 1
}
if ((`$lines -match '\bVersion\s+Available\b' -and `$process -eq `$null)) {
    `$verInstalled, `$verAvailable = (-split `$lines[-1])[-3,-2]
    Write-Host "Application update available for $Name. Current version is `$verInstalled, version available is `$verAvailable"
    [PSCustomObject]@{
        Name = "$Name"
        InstalledVersion = `$verInstalled
        AvailableVersion = `$verAvailable
        Status = "UpdateAvailable"
    }
    exit 1
}
"@
    } else {
@"
if (`$lines -match '\bVersion\s+Available\b') {
    `$verInstalled, `$verAvailable = (-split `$lines[-1])[-3,-2]
    Write-Host "Application update available for $Name. Current version is `$verInstalled, version available is `$verAvailable"
    [PSCustomObject]@{
        Name = "$Name"
        InstalledVersion = `$verInstalled
        AvailableVersion = `$verAvailable
        Status = "UpdateAvailable"
    }
    exit 1
}
"@
    }

@"
<#
.SYNOPSIS
    Detects if $Name has an available update via winget.

.DESCRIPTION
    Detection script for Intune Proactive Remediation.
    Checks if $Name has an update available using winget.
    Exit 1 = Update available (triggers remediation)
    Exit 0 = Up to date or not installed

.NOTES
    Auto-generated by New-BulkWingetUpdater.ps1
    App: $Name
    WingetID: $ID
    Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#>

# Display name of your application
`$name = '$Name'
# Winget ID for the package
`$ID = '$ID'
# Name of the running process
`$AppProcess = "$Process"

# Location of the winget exe
`$wingetExe = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe\winget.exe" -ErrorAction SilentlyContinue

if (-not `$wingetExe) {
    Write-Host "Winget not found on this system."
    exit 0
}

`$systemContext = `$wingetExe[-1].Path

# Create the sysget alias so winget can be run as SYSTEM
New-Alias -Name sysget -Value "`$systemContext" -Force

try {
    # Get info on the app
    `$lines = sysget list --accept-source-agreements --id `$ID 2>&1

    # Check if app is not installed
    if (`$lines -match "No installed package found") {
        Write-Host "`$name is not installed on this device."
        exit 0
    }

    $processCheck

    # App is up to date
    if (`$lines -match '\d+(\.\d+)+') {
        `$versionInstalled = (-split `$lines[-1])[-2]
        [PSCustomObject]@{
            Name = "$Name"
            InstalledVersion = `$versionInstalled
            Status = "UpToDate"
        }
        Write-Host "`$name is up to date (version `$versionInstalled)."
        exit 0
    }

    Write-Host "`$name is up to date."
    exit 0
}
catch {
    `$errMsg = `$_.Exception.Message
    Write-Error `$errMsg
    exit 1
}
"@
}

function New-RemediateScript {
    param(
        [string]$Name,
        [string]$ID,
        [string]$Process,
        [bool]$Force = $false
    )

    $processCheck = if(-not $Force) {
@"
# Check if app is running
`$process = Get-Process -Name "`$AppProcess" -ErrorAction SilentlyContinue
if (`$process -ne `$null) {
    Write-Host "`$name is currently running, will try again later."
    exit 1
}
"@
    } else {
@"
# Force update enabled - will update even if running
Write-Verbose -Verbose "Force update enabled"
"@
    }

@"
<#
.SYNOPSIS
    Remediates $Name by installing available updates via winget.

.DESCRIPTION
    Remediation script for Intune Proactive Remediation.
    Installs updates for $Name using winget in silent mode.
    Exit 0 = Update successful
    Exit 1 = Update failed or app is running

.NOTES
    Auto-generated by New-BulkWingetUpdater.ps1
    App: $Name
    WingetID: $ID
    Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#>

# Display name of your application
`$name = '$Name'
# Winget ID for the package
`$ID = '$ID'
# Name of the running process
`$AppProcess = "$Process"

# Location of the winget exe
`$wingetExe = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe\winget.exe" -ErrorAction SilentlyContinue

if (-not `$wingetExe) {
    Write-Error "Winget not found on this system."
    exit 1
}

`$systemContext = `$wingetExe[-1].Path

# Create the sysget alias so winget can be run as SYSTEM
New-Alias -Name sysget -Value "`$systemContext" -Force

try {
    # Get current status
    `$lines = sysget list --accept-source-agreements --id `$ID 2>&1

    if (`$lines -match '\bVersion\s+Available\b') {
        `$verInstalled, `$verAvailable = (-split `$lines[-1])[-3,-2]
        Write-Host "Updating `$name from `$verInstalled to `$verAvailable"
    }

    $processCheck

    # Run the upgrade
    Write-Host "Installing update for `$name..."
    `$upgradeResult = sysget upgrade -e --id `$ID --silent --accept-package-agreements --accept-source-agreements 2>&1

    # Verify installation
    Start-Sleep -Seconds 5
    `$lines = sysget list --accept-source-agreements --id `$ID 2>&1

    if (`$lines -match '\d+(\.\d+)+') {
        `$versionInstalled = (-split `$lines[-1])[-2]
        [PSCustomObject]@{
            Name = "$Name"
            InstalledVersion = `$versionInstalled
            Status = "Updated"
        }
        Write-Host "`$name successfully updated to version `$versionInstalled"
        exit 0
    }

    Write-Host "`$name update completed."
    exit 0
}
catch {
    `$errMsg = `$_.Exception.Message
    Write-Error `$errMsg
    exit 1
}
"@
}

function New-WingetScripts {
    param(
        [string]$Name,
        [string]$ID,
        [string]$Process,
        [string]$Path,
        [bool]$Force = $false
    )

    # Create output directory
    $appFolder = Join-Path $Path $Name
    if(-not (Test-Path $appFolder)) {
        New-Item -ItemType Directory -Path $appFolder -Force | Out-Null
    }

    # Generate detect script
    $detectScript = New-DetectScript -Name $Name -ID $ID -Process $Process -Force $Force
    $detectPath = Join-Path $appFolder "detect.ps1"
    $detectScript | Out-File -FilePath $detectPath -Encoding UTF8 -Force

    # Generate remediate script
    $remediateScript = New-RemediateScript -Name $Name -ID $ID -Process $Process -Force $Force
    $remediatePath = Join-Path $appFolder "remediate.ps1"
    $remediateScript | Out-File -FilePath $remediatePath -Encoding UTF8 -Force

    Write-ColorOutput "  Created: $appFolder" -Level Success
    Write-ColorOutput "    - detect.ps1" -Level Info
    Write-ColorOutput "    - remediate.ps1" -Level Info
}

# Main execution
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "  Winget Remediation Script Generator" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

if($GenerateBatch) {
    if(-not (Test-Path $CSVPath)) {
        Write-ColorOutput "ERROR: CSV file not found: $CSVPath" -Level Error
        exit 1
    }

    $apps = Import-Csv -Path $CSVPath
    Write-ColorOutput "Generating scripts for $($apps.Count) applications...`n" -Level Info

    foreach($app in $apps) {
        Write-Host "Processing: $($app.AppName)" -ForegroundColor Cyan
        New-WingetScripts -Name $app.AppName -ID $app.WingetID -Process $app.ProcessName -Path $OutputPath -Force:$ForceUpdate
    }

    Write-ColorOutput "`nBatch generation complete!" -Level Success
    Write-ColorOutput "Output location: $OutputPath" -Level Info
}
else {
    Write-Host "Generating scripts for: $AppName" -ForegroundColor Cyan
    New-WingetScripts -Name $AppName -ID $WingetID -Process $ProcessName -Path $OutputPath -Force:$ForceUpdate
    Write-ColorOutput "`nScript generation complete!" -Level Success
}

Write-Host "`n========================================`n" -ForegroundColor Cyan
