<#
.SYNOPSIS
    Generates Intune Proactive Remediation scripts for Winget package updates.
.DESCRIPTION
    Creates a pair of detection and remediation scripts for use with Intune Proactive
    Remediations to keep applications up-to-date using Winget in SYSTEM context.

    The generated scripts will:
    - Detect if the specified app needs an update
    - Silently update the app using Winget
    - Run in SYSTEM context
    - Log all actions
    - Handle errors gracefully

    Useful for keeping apps like Google Chrome, Firefox, Microsoft Edge, Adobe Reader,
    7-Zip, or any Winget-available package current. Generated files are written to
    -OutputFolder and are safe to regenerate (existing files are overwritten).
.PARAMETER PackageId
    The Winget package ID (e.g., "Google.Chrome", "Mozilla.Firefox").
    Prompts interactively when omitted.
.PARAMETER OutputFolder
    Where to save the generated scripts. Default: Desktop\WingetRemediations\<PackageId>.
.PARAMETER AppDisplayName
    Friendly name for the app (optional, used in script comments). Derived from PackageId
    when omitted.
.PARAMETER IncludeReadme
    Generate a README with deployment instructions.
.EXAMPLE
    PS C:\> .\New-WingetRemediationScript.ps1 -PackageId "Google.Chrome"
    Generates detection and remediation scripts for Google Chrome.
.EXAMPLE
    PS C:\> .\New-WingetRemediationScript.ps1 -PackageId "Mozilla.Firefox" -AppDisplayName "Firefox Browser" `
        -IncludeReadme
    Generates scripts with a custom display name and a deployment README.
.NOTES
    File Name   : New-WingetRemediationScript.ps1
    Author      : Bug-Free Umbrella
    Prerequisite: PowerShell 7.0
    Version     : 1.0.0
    Date        : 2026-08-23

    No Graph API connection needed - this is a local script generator.
    Output scripts are ready to upload to Intune Proactive Remediations.
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory = $false)]
    [string]$PackageId,

    [Parameter(Mandatory = $false)]
    [string]$OutputFolder,

    [Parameter(Mandatory = $false)]
    [string]$AppDisplayName,

    [Parameter(Mandatory = $false)]
    [switch]$IncludeReadme
)

$ErrorActionPreference = 'Stop'

function Get-DetectionScriptContent {
    # Builds the Winget-based detection script body for the target package.
    [CmdletBinding()]
    param()

    return @"
<#
.SYNOPSIS
    Detection script for $AppDisplayName Winget update.

.DESCRIPTION
    Checks if $AppDisplayName has an available update via Winget.
    Returns exit code 1 if update is needed (triggers remediation).
    Returns exit code 0 if app is up-to-date (no remediation needed).

.NOTES
    Generated by New-WingetRemediationScript.ps1
    Package ID: $PackageId
    Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#>

`$packageId = "$PackageId"
`$logPath = "`$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\WingetRemediation_`$packageId.log"

function Write-Log {
    param([string]`$Message)
    `$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    `$logMessage = "[`$timestamp] [DETECT] `$Message"
    Add-Content -Path `$logPath -Value `$logMessage
}

try {
    Write-Log "Starting detection for `$packageId"

    # Check if Winget is available
    `$wingetPath = (Get-Command winget.exe -ErrorAction SilentlyContinue).Source

    if (-not `$wingetPath) {
        Write-Log "Winget not found - may need installation"
        # Try common paths
        `$wingetPath = "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller*_x64__8wekyb3d8bbwe\winget.exe"
        `$wingetExe = Get-Item `$wingetPath -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending | Select-Object -First 1

        if (`$wingetExe) {
            `$wingetPath = `$wingetExe.FullName
            Write-Log "Found Winget at: `$wingetPath"
        }
        else {
            Write-Log "ERROR: Winget not available on this system"
            Write-Output "Winget not available"
            exit 0  # Compliant - cannot remediate without winget
        }
    }

    # Check for available updates
    Write-Log "Checking for updates for `$packageId"

    `$upgradeList = & `$wingetPath upgrade --id `$packageId --accept-source-agreements 2>&1

    if (`$LASTEXITCODE -ne 0) {
        Write-Log "Package `$packageId not found or error occurred"
        Write-Output "Package not found"
        exit 0  # Compliant - package not installed or not found
    }

    # Parse output to see if update is available
    `$upgradeAvailable = `$false

    if (`$upgradeList -match `$packageId) {
        # Package found in upgrade list means update is available
        `$upgradeAvailable = `$true
        Write-Log "Update available for `$packageId"
    }
    else {
        Write-Log "No update available for `$packageId"
    }

    if (`$upgradeAvailable) {
        Write-Log "DETECTION: Update needed - remediation required"
        Write-Output "Update available"
        exit 1  # Non-compliant - trigger remediation
    }
    else {
        Write-Log "DETECTION: App is up-to-date"
        Write-Output "Up-to-date"
        exit 0  # Compliant - no action needed
    }
}
catch {
    Write-Log "ERROR: `$(`$_.Exception.Message)"
    Write-Output "Detection error"
    exit 1  # Error during detection
}
"@
}

function Get-RemediateScriptContent {
    # Builds the Winget-based silent-update remediation script body.
    [CmdletBinding()]
    param()

    return @"
<#
.SYNOPSIS
    Remediation script for $AppDisplayName Winget update.

.DESCRIPTION
    Updates $AppDisplayName to the latest version using Winget in SYSTEM context.
    Runs silently and logs all actions.

.NOTES
    Generated by New-WingetRemediationScript.ps1
    Package ID: $PackageId
    Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#>

`$packageId = "$PackageId"
`$logPath = "`$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\WingetRemediation_`$packageId.log"

function Write-Log {
    param([string]`$Message)
    `$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    `$logMessage = "[`$timestamp] [REMEDIATE] `$Message"
    Add-Content -Path `$logPath -Value `$logMessage
}

try {
    Write-Log "Starting remediation for `$packageId"

    # Check if Winget is available
    `$wingetPath = (Get-Command winget.exe -ErrorAction SilentlyContinue).Source

    if (-not `$wingetPath) {
        Write-Log "Winget not found - trying common paths"
        `$wingetPath = "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller*_x64__8wekyb3d8bbwe\winget.exe"
        `$wingetExe = Get-Item `$wingetPath -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending | Select-Object -First 1

        if (`$wingetExe) {
            `$wingetPath = `$wingetExe.FullName
            Write-Log "Found Winget at: `$wingetPath"
        }
        else {
            Write-Log "ERROR: Winget not available - cannot remediate"
            Write-Output "Winget not available"
            exit 1  # Failed
        }
    }

    Write-Log "Winget path: `$wingetPath"

    # Perform upgrade
    Write-Log ("Executing: winget upgrade --id `$packageId --silent " +
        "--accept-package-agreements --accept-source-agreements")

    `$upgradeArgs = @(
        'upgrade', '--id', `$packageId, '--silent',
        '--accept-package-agreements', '--accept-source-agreements'
    )
    `$upgradeOutput = & `$wingetPath @upgradeArgs 2>&1
    `$upgradeExitCode = `$LASTEXITCODE

    # Log output
    Write-Log "Winget output: `$upgradeOutput"
    Write-Log "Winget exit code: `$upgradeExitCode"

    # Check result
    if (`$upgradeExitCode -eq 0) {
        Write-Log "SUCCESS: `$packageId updated successfully"
        Write-Output "Update successful"
        exit 0  # Success
    }
    elseif (`$upgradeExitCode -eq -1978335189) {
        # No applicable update found (already up to date)
        Write-Log "INFO: No update needed - already up-to-date"
        Write-Output "Already up-to-date"
        exit 0  # Success (nothing to do)
    }
    else {
        Write-Log "ERROR: Update failed with exit code `$upgradeExitCode"
        Write-Output "Update failed: `$upgradeExitCode"
        exit 1  # Failed
    }
}
catch {
    Write-Log "ERROR: Exception during remediation: `$(`$_.Exception.Message)"
    Write-Output "Remediation error"
    exit 1  # Failed
}
"@
}

function Get-ReadmeContent {
    # Builds the deployment instructions README for the generated pair.
    [CmdletBinding()]
    param()

    return @"
# Winget Proactive Remediation for $AppDisplayName

**Package ID:** $PackageId
**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

## Overview

This proactive remediation automatically keeps **$AppDisplayName** up-to-date on managed devices using Winget.

## Files

- **detect.ps1** - Checks if an update is available
- **remediate.ps1** - Updates the application silently

## Deployment Instructions

### 1. Upload to Intune

1. Go to **Intune > Devices > Scripts and remediations**
2. Click **+ Create** under **Proactive remediations**
3. Enter a name: `Winget Update - $AppDisplayName`
4. Upload **detect.ps1** as the detection script
5. Upload **remediate.ps1** as the remediation script

### 2. Script Settings

Configure the following settings:

| Setting | Value |
|---------|-------|
| **Run this script using the logged-on credentials** | No |
| **Enforce script signature check** | No |
| **Run script in 64-bit PowerShell** | Yes |

### 3. Assignment

- Assign to device groups that need $AppDisplayName
- Recommended schedule: **Daily** or **Every 3 days**

### 4. Monitoring

Check logs on devices at:
``````
C:\ProgramData\Microsoft\IntuneManagementExtension\Logs\WingetRemediation_$PackageId.log
``````

## Expected Behavior

- **Detection runs** on schedule
- If update available → **Remediation runs** automatically
- Update installs **silently** in background
- Logs all actions for troubleshooting

## Prerequisites

- Device has **Winget** installed (Windows 10 1809+ / Windows 11)
- Device has internet connectivity
- Application is installed on device

## Testing

Test manually on a device:
``````powershell
# Run detection
.\detect.ps1

# If exit code is 0, run remediation
.\remediate.ps1
``````

## Troubleshooting

### Winget Not Found
- Ensure Windows App Installer is installed from Microsoft Store
- Or deploy Winget via Intune app deployment

### Update Fails
- Check application is not running
- Verify internet connectivity
- Check Winget logs: `C:\ProgramData\Microsoft\IntuneManagementExtension\Logs\`

### Package Not Found
- Verify package ID is correct
- Search for packages at https://winget.run
- Test package ID manually: `winget show $PackageId`

## Additional Notes

- Runs in **SYSTEM context** (no user interaction)
- Supports **silent installations** only
- App must be available in Winget repository
- Updates to **latest stable version**

---

**Generated by:** New-WingetRemediationScript.ps1
**Support:** Check Intune proactive remediation logs for execution details
"@
}

function Main {
    # Justification: Write-Host with colors is mandated by the relaunch output-prefix standard.
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingWriteHost', '')]
    [CmdletBinding(SupportsShouldProcess)]
    param()

    try {
        Write-Host "`n========================================" -ForegroundColor Cyan
        Write-Host "Winget Proactive Remediation Generator" -ForegroundColor Cyan
        Write-Host "========================================`n" -ForegroundColor Cyan

        # Prompt for Package ID if not provided
        if (-not $PackageId) {
            Write-Host "Enter the Winget Package ID to create remediation for:" -ForegroundColor Yellow
            Write-Host "Examples:" -ForegroundColor White
            Write-Host "  Google.Chrome" -ForegroundColor White
            Write-Host "  Mozilla.Firefox" -ForegroundColor White
            Write-Host "  Microsoft.Edge" -ForegroundColor White
            Write-Host "  Adobe.Acrobat.Reader.64-bit" -ForegroundColor White
            Write-Host "  7zip.7zip" -ForegroundColor White
            Write-Host "  Microsoft.VisualStudioCode" -ForegroundColor White
            Write-Host "`nTip: Search for packages at https://winget.run" -ForegroundColor Cyan

            $PackageId = Read-Host "`nPackage ID"

            if ([string]::IsNullOrWhiteSpace($PackageId)) {
                Write-Host "[-] Package ID cannot be empty." -ForegroundColor Red
                return 1
            }
        }

        # Set display name if not provided
        if (-not $AppDisplayName) {
            # Try to extract a friendly name from Package ID
            $AppDisplayName = $PackageId -replace '\.', ' '
        }

        # Set output folder
        if (-not $OutputFolder) {
            $OutputFolder = Join-Path $env:USERPROFILE "Desktop\WingetRemediations\$($PackageId -replace '\.', '_')"
        }

        # Create output folder
        if (-not (Test-Path -LiteralPath $OutputFolder)) {
            if ($PSCmdlet.ShouldProcess($OutputFolder, 'Create output folder')) {
                New-Item -Path $OutputFolder -ItemType Directory -Force -ErrorAction Stop | Out-Null
            }
        }

        Write-Host "[+] Package ID: $($PackageId)" -ForegroundColor Green
        Write-Host "[+] Display Name: $($AppDisplayName)" -ForegroundColor Green
        Write-Host "[+] Output Folder: $($OutputFolder)" -ForegroundColor Green

        # Generate scripts
        $detectScript = Get-DetectionScriptContent -ErrorAction Stop
        $remediateScript = Get-RemediateScriptContent -ErrorAction Stop

        # Save scripts
        $detectPath = Join-Path $OutputFolder "detect.ps1"
        $remediatePath = Join-Path $OutputFolder "remediate.ps1"

        if ($PSCmdlet.ShouldProcess($detectPath, 'Write detection script')) {
            $detectScript | Out-File -FilePath $detectPath -Encoding UTF8 -Force -ErrorAction Stop
            Write-Host "`n[+] Detection script created: $detectPath" -ForegroundColor Green
        }

        if ($PSCmdlet.ShouldProcess($remediatePath, 'Write remediation script')) {
            $remediateScript | Out-File -FilePath $remediatePath -Encoding UTF8 -Force -ErrorAction Stop
            Write-Host "[+] Remediation script created: $remediatePath" -ForegroundColor Green
        }

        # Generate README if requested
        if ($IncludeReadme) {
            $readmeContent = Get-ReadmeContent -ErrorAction Stop
            $readmePath = Join-Path $OutputFolder "README.md"

            if ($PSCmdlet.ShouldProcess($readmePath, 'Write README')) {
                $readmeContent | Out-File -FilePath $readmePath -Encoding UTF8 -Force -ErrorAction Stop
                Write-Host "[+] README created: $readmePath" -ForegroundColor Green
            }
        }

        # Display summary
        Write-Host "`n========================================" -ForegroundColor Cyan
        Write-Host "GENERATION COMPLETE!" -ForegroundColor Cyan
        Write-Host "========================================" -ForegroundColor Cyan
        Write-Host "`nNext Steps:" -ForegroundColor Yellow
        Write-Host "1. Review the generated scripts in: $($OutputFolder)" -ForegroundColor White
        Write-Host "2. Test on a device manually (optional)" -ForegroundColor White
        Write-Host "3. Upload to Intune > Devices > Scripts and remediations" -ForegroundColor White
        Write-Host "4. Configure to run as SYSTEM in 64-bit PowerShell" -ForegroundColor White
        Write-Host "5. Assign to device groups" -ForegroundColor White

        Write-Host "`nScript Settings for Intune:" -ForegroundColor Cyan
        Write-Host "  Run using logged-on credentials: No" -ForegroundColor White
        Write-Host "  Enforce script signature check: No" -ForegroundColor White
        Write-Host "  Run in 64-bit PowerShell: Yes" -ForegroundColor White

        # Open folder
        Write-Host "`n[*] Opening output folder..." -ForegroundColor Cyan
        try {
            Start-Process -FilePath $OutputFolder -ErrorAction Stop
        }
        catch {
            Write-Host "[!] Could not open output folder: $($_.Exception.Message)" -ForegroundColor Yellow
        }

        Write-Host "`n[+] Winget remediation scripts generated successfully!" -ForegroundColor Green
        return 0
    }
    catch {
        Write-Host "[-] Error: $($_.Exception.Message)" -ForegroundColor Red
        return 1
    }
}

# Execute only when run as a script; dot-sourcing (Pester tests, module builds) skips execution.
if ($MyInvocation.InvocationName -ne '.') { exit (Main) }
