<#
.SYNOPSIS
    New employee workstation setup workflow

.DESCRIPTION
    This example demonstrates a complete onboarding workflow for new employees,
    including device enrollment, application deployment, and compliance configuration.

.NOTES
    Copyright (c) 2025 bug-free-umbrella contributors
    Licensed under Apache License 2.0
    https://github.com/Carme99/bug-free-umbrella

.EXAMPLE
    .\new-employee-setup.ps1 -EmployeeName "John Doe" -Department "Sales"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$EmployeeName,

    [Parameter(Mandatory = $true)]
    [string]$Department,

    [Parameter(Mandatory = $false)]
    [string]$ComputerName = $env:COMPUTERNAME
)

# Define the root path to the scripts directory
$ScriptRoot = Join-Path -Path $PSScriptRoot -ChildPath "..\..\scripts"

Write-Host "=== New Employee Onboarding Workflow ===" -ForegroundColor Cyan
Write-Host "Employee: $EmployeeName" -ForegroundColor Yellow
Write-Host "Department: $Department" -ForegroundColor Yellow
Write-Host "Computer: $ComputerName" -ForegroundColor Yellow
Write-Host ""

# Step 1: Device Inventory and Health Check
Write-Host "[1/6] Running device inventory and health check..." -ForegroundColor Green
try {
    & "$ScriptRoot\infrastructure\windows\monitoring\Monitor-ServerHealth.ps1" -QuickCheck
    Write-Host "✓ Device health check completed" -ForegroundColor Green
} catch {
    Write-Warning "Health check failed: $_"
}

# Step 2: Security Compliance Baseline
Write-Host "`n[2/6] Applying security compliance baseline..." -ForegroundColor Green
try {
    & "$ScriptRoot\security\compliance\frameworks\Invoke-SecurityComplianceScan.ps1" -Framework CIS
    Write-Host "✓ Security baseline scan completed" -ForegroundColor Green
} catch {
    Write-Warning "Security scan failed: $_"
}

# Step 3: BitLocker Encryption Check
Write-Host "`n[3/6] Verifying BitLocker encryption..." -ForegroundColor Green
try {
    & "$ScriptRoot\endpoints\intune\reporting\Get-BitLockerStatus.ps1"
    Write-Host "✓ BitLocker status verified" -ForegroundColor Green
} catch {
    Write-Warning "BitLocker check failed: $_"
}

# Step 4: Deploy Standard Applications (if Intune is available)
Write-Host "`n[4/6] Checking application deployment status..." -ForegroundColor Green
$StandardApps = @(
    "Microsoft 365 Apps for Enterprise",
    "Microsoft Teams",
    "Microsoft Edge"
)

foreach ($App in $StandardApps) {
    Write-Host "  - Checking: $App" -ForegroundColor Yellow
    # In production, this would check Intune deployment status
}

# Step 5: Configure Department-Specific Settings
Write-Host "`n[5/6] Applying department-specific configuration..." -ForegroundColor Green
switch ($Department) {
    "Sales" {
        Write-Host "  - Installing CRM applications" -ForegroundColor Yellow
        Write-Host "  - Configuring sales dashboards" -ForegroundColor Yellow
    }
    "IT" {
        Write-Host "  - Installing administrative tools" -ForegroundColor Yellow
        Write-Host "  - Granting elevated permissions" -ForegroundColor Yellow
    }
    "Finance" {
        Write-Host "  - Installing financial software" -ForegroundColor Yellow
        Write-Host "  - Applying enhanced security policies" -ForegroundColor Yellow
    }
    Default {
        Write-Host "  - Applying standard configuration" -ForegroundColor Yellow
    }
}

# Step 6: Generate Onboarding Report
Write-Host "`n[6/6] Generating onboarding report..." -ForegroundColor Green
$ReportPath = Join-Path -Path $env:TEMP -ChildPath "Onboarding_${EmployeeName}_$(Get-Date -Format 'yyyyMMdd').txt"
$Report = @"
EMPLOYEE ONBOARDING REPORT
==========================
Employee: $EmployeeName
Department: $Department
Computer: $ComputerName
Date: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

ONBOARDING TASKS COMPLETED:
✓ Device inventory and health check
✓ Security compliance baseline
✓ BitLocker encryption verification
✓ Application deployment
✓ Department-specific configuration

NEXT STEPS:
- Verify user can access email and Teams
- Test access to department-specific applications
- Schedule follow-up check in 24 hours
- Provide user with IT support contact information

This report generated by bug-free-umbrella automation
https://github.com/Carme99/bug-free-umbrella
"@

$Report | Out-File -FilePath $ReportPath -Encoding UTF8
Write-Host "✓ Report saved to: $ReportPath" -ForegroundColor Green

Write-Host "`n=== Onboarding Complete ===" -ForegroundColor Cyan
Write-Host "Please verify all applications are accessible and working correctly." -ForegroundColor Yellow
