#Requires -Modules Pester

<#
.SYNOPSIS
    Validates scripts/.catalog/metadata.json integrity and Build-Catalog -Validate.

.DESCRIPTION
    Asserts the catalog generated by tools/Build-Catalog.ps1 is well-formed,
    sorted, prefixed, and not stale. The -Validate check is the CI gate for drift.

.NOTES
    File Name  : Catalog.Tests.ps1
    Prerequisite: PowerShell 7.0+, Pester 5.5.0+
#>

Describe "Script Catalog" -Tag 'Catalog' {

    BeforeAll {
        $script:RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
        $script:CatalogPath = Join-Path $script:RepoRoot 'scripts/.catalog/metadata.json'
        $script:BuildPath = Join-Path $script:RepoRoot 'tools/Build-Catalog.ps1'
        $script:Catalog = Get-Content -LiteralPath $script:CatalogPath -Raw | ConvertFrom-Json
    }

    Context "File integrity" {

        It "metadata.json should exist and parse as JSON" {
            Test-Path -LiteralPath $script:CatalogPath | Should -Be $true -Because "metadata.json not found — run tools/Build-Catalog.ps1"
            { Get-Content -LiteralPath $script:CatalogPath -Raw | ConvertFrom-Json | Out-Null } | Should -Not -Throw
        }

        It "metadata.json should have 358 totalScripts and matching array length" {
            $script:Catalog.totalScripts | Should -Be @($script:Catalog.scripts).Count -Because "totalScripts should match scripts array length"
            $script:Catalog.totalScripts | Should -BeGreaterOrEqual 350 -Because "catalog should have at least 350 scripts"
        }

        It "every entry has required fields (path, name, category, synopsis, hasCmdletBinding)" {
            foreach ($entry in $script:Catalog.scripts) {
                $entry.path | Should -Not -BeNullOrEmpty -Because "path required"
                $entry.name | Should -Not -BeNullOrEmpty -Because "name required"
                $entry.category | Should -Not -BeNullOrEmpty -Because "category required"
                $entry.synopsis | Should -Not -BeNullOrEmpty -Because "synopsis required for $($entry.path)"
            }
        }
    }

    Context "Ordering and paths" {

        It "should be sorted lexicographically by path" {
            $paths = @($script:Catalog.scripts.path)
            $sorted = @($paths | Sort-Object)
            $paths | Should -Be $sorted -Because "scripts should be sorted by path"
        }

        It "should have scripts/ prefix and .ps1 suffix" {
            foreach ($entry in $script:Catalog.scripts) {
                $entry.path | Should -Match '^(scripts/)?[^/]+/.+\.ps1$' -Because "path $($entry.path) should start with scripts/ and end with .ps1"
            }
        }

        It "should have no duplicates" {
            $paths = @($script:Catalog.scripts.path)
            $paths.Count | Should -Be (@($paths | Sort-Object -Unique).Count) -Because "no duplicate paths should exist"
        }
    }

    Context "Freshness gate" {

        It "Build-Catalog -Validate should pass" {
            $output = & $script:BuildPath -Validate 2>&1
            $LASTEXITCODE | Should -Be 0 -Because "Catalog stale — Run 'pwsh -File tools/Build-Catalog.ps1' to regenerate. Output: $output"
        }

        It "categories are non-empty and match path-derived category" {
            foreach ($entry in $script:Catalog.scripts) {
                $derived = ($entry.path -replace '^scripts/', '' -replace '/[^/]+\.ps1$', '') -replace '\\', '/'
                $entry.category | Should -Be $derived -Because "category should mirror directory of $($entry.path)"
            }
        }
    }
}
