@{
    # --- Identity ---
    ModuleVersion      = '5.0.0'
    GUID               = '7cc494cc-4523-4630-a69e-12b77001c0f0'
    Author             = 'Carme99'
    CompanyName        = 'Carme99'
    Copyright          = '(c) Carme99. Licensed under Apache-2.0.'
    Description        = '358 PowerShell scripts as importable module'

    # --- Requirements ---
    PowerShellVersion  = '5.1'
    CompatiblePSEditions = @('Desktop', 'Core')
    RequiredModules    = @()
    PowerShellHostName = ''
    PowerShellHostVersion = ''
    DotNetFrameworkVersion = ''
    CLRVersion         = ''

    # --- Loading ---
    RootModule         = 'BugFreeUmbrella.psm1'
    ScriptsToProcess   = @()
    TypesToProcess     = @()
    FormatsToProcess   = @()
    NestedModules      = @()

    # --- Exports ---
    FunctionsToExport  = @(
        'Add-LenovoFriendlyModelNames',
        'Backup-GroupPolicies',
        'Backup-IISConfiguration',
        'Block-AMDDriver',
        'Compare-ConfigurationDrift',
        'Export-IntuneConfiguration',
        'Export-WingetPackageList',
        'Find-GPOConflicts',
        'Find-InactiveADComputers',
        'Find-PolicyConflicts',
        'Find-StaleDevices',
        'Get-ADHealthCheck',
        'Get-ADUserAudit',
        'Get-AntivirusStatus',
        'Get-AppInstallationStatus',
        'Get-AppInstallErrorReport',
        'Get-AutopilotDeploymentReport',
        'Get-AWSResourceInventory',
        'Get-AzureADGuestAudit',
        'Get-AzureADLicenseReport',
        'Get-AzureResourceHealth',
        'Get-BackupStatus',
        'Get-BatteryHealth',
        'Get-BitLockerStatus',
        'Get-BUScript',
        'Get-DefenderO365ThreatReport',
        'Get-DeviceComplianceReport',
        'Get-DeviceGroupMembership',
        'Get-DeviceHealthScore',
        'Get-DiskReport',
        'Get-DistributionListAudit',
        'Get-DockerHealthCheck',
        'Get-EventLogReport',
        'Get-ExchangeServerHealth',
        'Get-ExpiredCertificates',
        'Get-FailedLoginReport',
        'Get-FirewallRulesReport',
        'Get-GPOReport',
        'Get-HyperVHealth',
        'Get-IISHealthCheck',
        'Get-IISLogAnalyzer',
        'Get-InactiveUserReport',
        'Get-IntuneDevicePrimaryUsers',
        'Get-KubernetesHealthCheck',
        'Get-LargeFilesReport',
        'Get-LocalAdminAudit',
        'Get-M365UserInfo',
        'Get-MailboxHealth',
        'Get-MailFlowAnalysis',
        'Get-MDEDeviceHealth',
        'Get-MySQLHealth',
        'Get-NetworkConfiguration',
        'Get-OneDriveUsageReport',
        'Get-OpenPortScan',
        'Get-PerformanceReport',
        'Get-PerformanceTrends',
        'Get-PolicyAssignmentReport',
        'Get-PostgreSQLHealth',
        'Get-PowerPlatformGovernance',
        'Get-PrintServerHealth',
        'Get-SecurityBaseline',
        'Get-SecurityEventAudit',
        'Get-ServiceAccountAudit',
        'Get-SharedMailboxReport',
        'Get-SoftwareInventory',
        'Get-SoftwareLicenseCompliance',
        'Get-SQLServerHealth',
        'Get-SystemHealthCheck',
        'Get-SystemResourceTrends',
        'Get-TeamsReport',
        'Get-USBDeviceAudit',
        'Get-UserAccessReport',
        'Get-UserDeviceAffinity',
        'Get-UserLockoutReport',
        'Get-UserMailboxPermissions',
        'Get-UserMailRules',
        'Get-VMBackupCompliance',
        'Get-VMSecurityConfig',
        'Get-VMwareHealth',
        'Get-WindowsUpdateCompliance',
        'Get-WingetUpdateCompliance',
        'Install-TeamsAVD',
        'Install-TeamsAVDTests',
        'Invoke-AdobeRum',
        'Invoke-AnalyzeBuildPerformance',
        'Invoke-APDetection',
        'Invoke-APRemediation',
        'Invoke-BUScript',
        'Invoke-DeviceBulkActions',
        'Invoke-DisableWindowsUpdateAccess',
        'Invoke-DoNotConnectToWindowsUpdateInternetLocations',
        'Invoke-Drivers',
        'Invoke-FixBitLockerKeyBackup',
        'Invoke-GenerateWingetScripts',
        'Invoke-ManageFirewallRules',
        'Invoke-ManageQuarantinedEmails',
        'Invoke-ManageQuarantinedEmailsTests',
        'Invoke-ManageRestorePoints',
        'Invoke-MonitorAzureAPIManagement',
        'Invoke-MonitorAzureDevOpsPipelines',
        'Invoke-MonitorAzureKeyVaults',
        'Invoke-MonitorAzureResources',
        'Invoke-MonitorGitHubActions',
        'Invoke-MonitorGitLabCI',
        'Invoke-MonitorMongoDBHealth',
        'Invoke-MonitorServerHealth',
        'Invoke-NoAutoUpdate',
        'Invoke-RemediationCheckApplicationCrashes',
        'Invoke-RemediationCheckBatteryHealth',
        'Invoke-RemediationCheckBootPerformance',
        'Invoke-RemediationCheckDefenderHealthStatus',
        'Invoke-RemediationCheckDeviceHealthScore',
        'Invoke-RemediationCheckDeviceUptime',
        'Invoke-RemediationCheckDiskHealth',
        'Invoke-RemediationCheckHardwareErrors',
        'Invoke-RemediationCheckLocalAdminAccounts',
        'Invoke-RemediationCheckMemoryDiagnostics',
        'Invoke-RemediationCheckMicrosoftStoreAppsHealth',
        'Invoke-RemediationCheckOutdatedCriticalApps',
        'Invoke-RemediationCheckOutdatedCriticalAppsPriorityOnly',
        'Invoke-RemediationCheckPageFileConfiguration',
        'Invoke-RemediationCheckSecurityBaseline',
        'Invoke-RemediationCheckServiceFailures',
        'Invoke-RemediationCheckSharedFolders',
        'Invoke-RemediationCheckSystemEventErrors',
        'Invoke-RemediationCheckSystemStabilityIndex',
        'Invoke-RemediationCheckTPMStatus',
        'Invoke-RemediationCheckUnexpectedReboots',
        'Invoke-RemediationCheckWindowsActivationGracePeriod',
        'Invoke-RemediationFixBitLockerNotEscrowedKeys',
        'Invoke-RemediationFixBrokenShortcuts',
        'Invoke-RemediationFixCertificateExpiry',
        'Invoke-RemediationFixCredentialManager',
        'Invoke-RemediationFixDiskSpace',
        'Invoke-RemediationFixDNSCache',
        'Invoke-RemediationFixEdgeCacheSize',
        'Invoke-RemediationFixEventLogSize',
        'Invoke-RemediationFixNetworkAdapterPowerManagement',
        'Invoke-RemediationFixOneDriveKnownFolderMove',
        'Invoke-RemediationFixOutdatedDrivers',
        'Invoke-RemediationFixPowerShellExecutionPolicy',
        'Invoke-RemediationFixPrintSpooler',
        'Invoke-RemediationFixSMBv1Protocol',
        'Invoke-RemediationFixStaleProfiles',
        'Invoke-RemediationFixStartMenuLayout',
        'Invoke-RemediationFixSystemFileCorruption',
        'Invoke-RemediationFixTaskSchedulerCorruption',
        'Invoke-RemediationFixTeamsCache',
        'Invoke-RemediationFixTempFiles',
        'Invoke-RemediationFixTimeSync',
        'Invoke-RemediationFixWindowsLicenseActivation',
        'Invoke-RemediationFixWindowsPerformanceRecorder',
        'Invoke-RemediationFixWindowsSearch',
        'Invoke-RemediationFixWindowsStoreLicensing',
        'Invoke-RemediationFixWindowsUpdateRebootPending',
        'Invoke-RemediationFixWindowsUpdateStuck',
        'Invoke-RemediationKeyboardLayout',
        'Invoke-RemediationLanguagePackAudit',
        'Invoke-RemediationRegionLanguageSettings',
        'Invoke-Sccm',
        'Invoke-SecurityComplianceScan',
        'Invoke-TemplatesWinget',
        'Invoke-Uptime',
        'Invoke-UseWUServer',
        'Invoke-V1LegacyWinget',
        'Invoke-V2ForceCloseWinget',
        'Invoke-V2StandardWinget',
        'Invoke-V3',
        'Invoke-V3ForceCloseWinget',
        'Invoke-V3MaintenanceWindowWinget',
        'Invoke-V3StandardWinget',
        'Invoke-V4',
        'Invoke-V5',
        'Invoke-Winget1Password',
        'Invoke-WingetAdobeReader32bit',
        'Invoke-WingetAdobeReader64bit',
        'Invoke-WingetAzureCLI',
        'Invoke-WingetCpp2008Redist',
        'Invoke-WingetCpp2010Redist',
        'Invoke-WingetCpp2012Redist',
        'Invoke-WingetCpp2013RedistX64',
        'Invoke-WingetCpp2013RedistX86',
        'Invoke-WingetCpp20152019RedistX64',
        'Invoke-WingetCpp20152019RedistX86',
        'Invoke-WingetDiscord',
        'Invoke-WingetEdgeWebView2',
        'Invoke-WingetFirefox',
        'Invoke-WingetGit',
        'Invoke-WingetGoogleChrome',
        'Invoke-WingetLenovoDockManager',
        'Invoke-WingetLenovoSystemUpdate',
        'Invoke-WingetMicrosoftTeams',
        'Invoke-WingetNotepadPlusPlus',
        'Invoke-WingetOBS',
        'Invoke-WingetOhMyPosh',
        'Invoke-WingetPowerShell7MaintenanceWindow',
        'Invoke-WingetRemoteDesktop',
        'Invoke-WingetSevenZip',
        'Invoke-WingetSlack',
        'Invoke-WingetSSMS',
        'Invoke-WingetTeamViewerFull',
        'Invoke-WingetTeamViewerFullForceClose',
        'Invoke-WingetTeamViewerHost',
        'Invoke-WingetVisualStudioCode',
        'Invoke-WingetVisualStudioPro2019',
        'Invoke-WingetVisualStudioPro2022',
        'Invoke-WingetVLCMediaPlayer',
        'Invoke-WingetWinSCP',
        'Invoke-WingetZoom',
        'Invoke-WUServer',
        'New-AzureComputeGalleryImage',
        'New-BulkWingetUpdater',
        'New-IntuneWinPackage',
        'New-WeeklyRebootSchedule',
        'New-Win32AppTemplate',
        'New-WingetRemediationScript',
        'New-WingetSourceConfig',
        'Optimize-AzureVMs',
        'Optimize-DockerCleanup',
        'Optimize-IISConfiguration',
        'Optimize-ServerStorage',
        'Optimize-WindowsServices',
        'Optimize-WsusServer',
        'Register-BUCompleter',
        'Remove-SysprepBlockers',
        'Remove-USlangpack',
        'Remove-USLanguagePack',
        'Reset-NetworkStack',
        'Reset-WindowsUpdate',
        'Set-EnglishUKRegion',
        'Set-MailboxRegionalSettings',
        'Set-OneDriveRegionalSettings',
        'Set-OrganizationDefaults',
        'Set-PowerPlatformRegionalSettings',
        'Set-SiteRegionalSettings',
        'Set-TeamsRegionalSettings',
        'Set-UserLanguageSettings',
        'Sync-UserGroupToPrimaryDeviceGroup',
        'Test-AdobeRum',
        'Test-APIHealth',
        'Test-BackupIntegrity',
        'Test-BicepTemplates',
        'Test-BitLockerKeyBackup',
        'Test-CertificateExpiration',
        'Test-CISBenchmark',
        'Test-DisableWindowsUpdateAccess',
        'Test-DoNotConnectToWindowsUpdateInternetLocations',
        'Test-Drivers',
        'Test-IntuneConnectivity',
        'Test-IntuneConnectivityTests',
        'Test-NetworkConnectivity',
        'Test-NetworkDiagnostics',
        'Test-NoAutoUpdate',
        'Test-RemediationCheckApplicationCrashes',
        'Test-RemediationCheckBatteryHealth',
        'Test-RemediationCheckBootPerformance',
        'Test-RemediationCheckDefenderHealthStatus',
        'Test-RemediationCheckDeviceHealthScore',
        'Test-RemediationCheckDeviceUptime',
        'Test-RemediationCheckDiskHealth',
        'Test-RemediationCheckHardwareErrors',
        'Test-RemediationCheckLocalAdminAccounts',
        'Test-RemediationCheckMemoryDiagnostics',
        'Test-RemediationCheckMicrosoftStoreAppsHealth',
        'Test-RemediationCheckOutdatedCriticalApps',
        'Test-RemediationCheckPageFileConfiguration',
        'Test-RemediationCheckSecurityBaseline',
        'Test-RemediationCheckServiceFailures',
        'Test-RemediationCheckSharedFolders',
        'Test-RemediationCheckSystemEventErrors',
        'Test-RemediationCheckSystemStabilityIndex',
        'Test-RemediationCheckTPMStatus',
        'Test-RemediationCheckUnexpectedReboots',
        'Test-RemediationCheckWindowsActivationGracePeriod',
        'Test-RemediationFixBitLockerNotEscrowedKeys',
        'Test-RemediationFixBrokenShortcuts',
        'Test-RemediationFixCertificateExpiry',
        'Test-RemediationFixCredentialManager',
        'Test-RemediationFixDiskSpace',
        'Test-RemediationFixDNSCache',
        'Test-RemediationFixEdgeCacheSize',
        'Test-RemediationFixEventLogSize',
        'Test-RemediationFixNetworkAdapterPowerManagement',
        'Test-RemediationFixOneDriveKnownFolderMove',
        'Test-RemediationFixOutdatedDrivers',
        'Test-RemediationFixPowerShellExecutionPolicy',
        'Test-RemediationFixPrintSpooler',
        'Test-RemediationFixSMBv1Protocol',
        'Test-RemediationFixStaleProfiles',
        'Test-RemediationFixStartMenuLayout',
        'Test-RemediationFixSystemFileCorruption',
        'Test-RemediationFixTaskSchedulerCorruption',
        'Test-RemediationFixTeamsCache',
        'Test-RemediationFixTempFiles',
        'Test-RemediationFixTimeSync',
        'Test-RemediationFixWindowsLicenseActivation',
        'Test-RemediationFixWindowsPerformanceRecorder',
        'Test-RemediationFixWindowsSearch',
        'Test-RemediationFixWindowsStoreLicensing',
        'Test-RemediationFixWindowsUpdateRebootPending',
        'Test-RemediationFixWindowsUpdateStuck',
        'Test-RemediationKeyboardLayout',
        'Test-RemediationLanguagePackAudit',
        'Test-RemediationRegionLanguageSettings',
        'Test-Sccm',
        'Test-SecurityFeatures',
        'Test-ServerConnectivity',
        'Test-ServerHardening',
        'Test-SystemIntegrity',
        'Test-TemplatesWinget',
        'Test-TerraformConfiguration',
        'Test-Uptime',
        'Test-UseWUServer',
        'Test-V1LegacyWinget',
        'Test-V2Winget',
        'Test-V3',
        'Test-V3Winget',
        'Test-V4',
        'Test-V5',
        'Test-Winget1Password',
        'Test-WingetAdobeReader32bit',
        'Test-WingetAdobeReader64bit',
        'Test-WingetAzureCLI',
        'Test-WingetCpp2008Redist',
        'Test-WingetCpp2010Redist',
        'Test-WingetCpp2012Redist',
        'Test-WingetCpp2013RedistX64',
        'Test-WingetCpp2013RedistX86',
        'Test-WingetCpp20152019RedistX64',
        'Test-WingetCpp20152019RedistX86',
        'Test-WingetDiscord',
        'Test-WingetEdgeWebView2',
        'Test-WingetFirefox',
        'Test-WingetGit',
        'Test-WingetGoogleChrome',
        'Test-WingetLenovoDockManager',
        'Test-WingetLenovoSystemUpdate',
        'Test-WingetMicrosoftTeams',
        'Test-WingetNotepadPlusPlus',
        'Test-WingetOBS',
        'Test-WingetOhMyPosh',
        'Test-WingetPowerShell7',
        'Test-WingetRemoteDesktop',
        'Test-WingetSevenZip',
        'Test-WingetSlack',
        'Test-WingetSSMS',
        'Test-WingetTeamViewerFull',
        'Test-WingetTeamViewerHost',
        'Test-WingetVisualStudioCode',
        'Test-WingetVisualStudioPro2019',
        'Test-WingetVisualStudioPro2022',
        'Test-WingetVLCMediaPlayer',
        'Test-WingetWinSCP',
        'Test-WingetZoom',
        'Test-WUServer',
        'Unblock-AMDDriver',
        'Update-AllAppsWinget',
        'Update-DotNetRuntimes',
        'Update-M365Apps',
        'Update-M365AppsOfficeApps'
    )
    CmdletsToExport    = @()
    VariablesToExport  = @()
    AliasesToExport    = @()

    # --- Gallery Metadata ---
    PrivateData        = @{
        PSData = @{
            Tags                       = @('Intune','M365','Azure','Security')
            LicenseUri                 = 'https://github.com/Carme99/bug-free-umbrella/blob/main/LICENSE'
            ProjectUri                 = 'https://github.com/Carme99/bug-free-umbrella'
            IconUri                    = ''
            ReleaseNotes               = '5.0.0 Hurricane - Platform'
            Prerelease                 = ''
            RequireLicenseAcceptance   = $false
            ExternalModuleDependencies = @()
        }
    }

    HelpInfoURI          = 'https://github.com/Carme99/bug-free-umbrella/tree/main/docs'
    DefaultCommandPrefix = ''
}
