<#
.SYNOPSIS
    Detects stale or orphaned credentials in Windows Credential Manager.

.DESCRIPTION
    Checks for stale application-created (generic) credentials that may be
    causing authentication issues or clutter. Windows domain credentials
    ('Domain:target=...') are never flagged.

.NOTES
    Author: Intune Admin
    Version: 1.1
    Intune Context: SYSTEM
    Exit 0: Credential Manager is healthy
    Exit 1: Stale credentials detected - remediation needed

    Context limitation: this script runs as SYSTEM, so cmdkey /list enumerates
    only the SYSTEM credential store - per-user credential stores are not
    visible from this context and are not checked.

    By-design credentials (virtualapp/didlogical, _MSLITE_, MicrosoftAccount,
    WindowsLive) are created and regenerated by Windows itself and are NOT
    staleness signals - they are deliberately excluded from detection and
    remediation (see https://learn.microsoft.com/en-us/answers/questions/2583991/).

    The target list below is shared with remediate.ps1 so that every flagged
    credential can actually be removed (the pair converges).
#>

try {
    # Generic (application-created) credential types. Windows domain credentials
    # ('Domain:target=...') are required for network authentication and are
    # deliberately excluded.
    $genericTypePatterns = @('LegacyGeneric:', 'LegacyDiscardable:')

    # Credentials Windows creates and regenerates by design - not staleness
    # signals. Never flag or delete these.
    $byDesignPatterns = @('virtualapp/didlogical', '_MSLITE_', 'MicrosoftAccount', 'WindowsLive')

    $issues = @()
    $staleCredentials = @()

    # Get stored credentials using cmdkey. Out-String coalesces the line-per-
    # object native output into a single newline-separated string so the
    # Target: regex matches each credential line individually (an array passed
    # to [regex]::Matches would be space-joined, collapsing all entries).
    $credList = cmdkey /list 2>&1 | Out-String

    if ($LASTEXITCODE -eq 0) {
        # Parse credential list
        $targetPattern = "Target:\s+(.+)"
        $matches = [regex]::Matches($credList, $targetPattern)

        foreach ($match in $matches) {
            $target = $match.Groups[1].Value.Trim()

            # Skip by-design credentials
            $isByDesign = $false
            foreach ($byDesign in $byDesignPatterns) {
                if ($target -match $byDesign) {
                    $isByDesign = $true
                    break
                }
            }
            if ($isByDesign) { continue }

            # Flag generic (app-created) credentials - the same set remediate.ps1 removes
            foreach ($typePattern in $genericTypePatterns) {
                if ($target -like "$typePattern*") {
                    $staleCredentials += $target
                    break
                }
            }
        }
    }

    if ($staleCredentials.Count -gt 0) {
        Write-Host "Potentially stale credentials detected:"
        foreach ($cred in $staleCredentials) {
            Write-Host "  - $cred"
        }
        exit 1
    }

    Write-Host "Credential Manager appears healthy"
    exit 0

}
catch {
    Write-Host "Error checking Credential Manager: $_"
    exit 1
}
