<#
.SYNOPSIS
    Removes stale or orphaned credentials.

.DESCRIPTION
    Removes stale application-created (generic) credentials from Windows
    Credential Manager. Uses the SAME target list as detect.ps1 so the pair
    converges. Windows domain credentials ('Domain:target=...') and by-design
    Windows credentials are never touched.

.NOTES
    Author: Intune Admin
    Version: 1.1
    Intune Context: SYSTEM
    Exit 0: Remediation successful

    Context limitation: this script runs as SYSTEM, so cmdkey /list enumerates
    only the SYSTEM credential store - per-user credential stores are not
    visible from this context and are not modified.

    By-design credentials (virtualapp/didlogical, _MSLITE_, MicrosoftAccount,
    WindowsLive) are created and regenerated by Windows itself and are NOT
    staleness signals - they are deliberately excluded from detection and
    remediation (see https://learn.microsoft.com/en-us/answers/questions/2583991/).
#>

try {
    # Generic (application-created) credential types - shared with detect.ps1.
    $genericTypePatterns = @('LegacyGeneric:', 'LegacyDiscardable:')

    # Credentials Windows creates and regenerates by design - never delete these.
    $byDesignPatterns = @('virtualapp/didlogical', '_MSLITE_', 'MicrosoftAccount', 'WindowsLive')

    $remediationActions = @()

    # Get stored credentials using cmdkey. Out-String coalesces the line-per-
    # object native output into a single newline-separated string so the
    # Target: regex matches each credential line individually (an array passed
    # to [regex]::Matches would be space-joined, collapsing all entries).
    $credList = cmdkey /list 2>&1 | Out-String

    if ($LASTEXITCODE -eq 0) {
        # Parse credential list
        $targetPattern = "Target:\s+(.+)"
        $matches = [regex]::Matches($credList, $targetPattern)

        foreach ($match in $matches) {
            $target = $match.Groups[1].Value.Trim()

            # Skip by-design credentials
            $isByDesign = $false
            foreach ($byDesign in $byDesignPatterns) {
                if ($target -match $byDesign) {
                    $isByDesign = $true
                    break
                }
            }
            if ($isByDesign) { continue }

            # Remove generic (app-created) credentials - same set detect.ps1 flags
            foreach ($typePattern in $genericTypePatterns) {
                if ($target -like "$typePattern*") {
                    try {
                        cmdkey /delete:"$target" | Out-Null
                        if ($LASTEXITCODE -eq 0) {
                            $remediationActions += "Removed stale credential: $target"
                        }
                    }
                    catch {
                        Write-Host "Warning: Could not remove credential $target : $_"
                    }
                    break
                }
            }
        }
    }

    if ($remediationActions.Count -gt 0) {
        Write-Host "Credential Manager remediation completed:"
        foreach ($action in $remediationActions) {
            Write-Host "  - $action"
        }
    }
    else {
        Write-Host "No stale credentials found to remove"
    }

    exit 0

}
catch {
    Write-Host "Error during Credential Manager remediation: $_"
    exit 1
}
