<#
.SYNOPSIS
    Removes stale or orphaned credentials from Windows Credential Manager.

.DESCRIPTION
    Removes stale application-created (generic) credentials from Windows
    Credential Manager via cmdkey.exe, using the SAME target list as detect.ps1 so
    the pair converges. Windows domain credentials ('Domain:target=...') and
    by-design Windows credentials are never touched. Each deletion is gated behind
    -WhatIf/-Confirm via SupportsShouldProcess. Re-running on an already-converged
    system finds nothing to remove, changes nothing and still exits 0 (idempotent).
    Exit codes: 0 = completed successfully (with or without removals), 1 = an
    unexpected error occurred.
    Context limitation: this script runs as SYSTEM, so cmdkey /list enumerates
    only the SYSTEM credential store - per-user credential stores are not visible
    from this context and are not modified.
    By-design credentials (virtualapp/didlogical, _MSLITE_, MicrosoftAccount,
    WindowsLive) are created and regenerated by Windows itself and are NOT
    staleness signals - they are deliberately excluded from detection and
    remediation (see https://learn.microsoft.com/en-us/answers/questions/2583991/).

.EXAMPLE
    PS C:\> .\Invoke-RemediationFixCredentialManager.ps1

    Deletes every stale generic credential found in the SYSTEM credential store.

.EXAMPLE
    PS C:\> .\Invoke-RemediationFixCredentialManager.ps1 -WhatIf

    Shows which stale credentials would be deleted without deleting anything.

.NOTES
    File Name  : Invoke-RemediationFixCredentialManager.ps1
    Author     : Intune Admin
    Prerequisite: PowerShell 7.0
    Version    : 1.0.0
    Date       : 2026-08-23
#>

[CmdletBinding(SupportsShouldProcess)]
param()

$ErrorActionPreference = 'Stop'

function Invoke-CmdKey {
    # Thin wrapper around the native cmdkey.exe executable; mock seam for Pester tests.
    param(
        [Parameter(ValueFromRemainingArguments)]
        [string[]]$Remaining
    )

    $output = & cmdkey.exe @Remaining 2>&1 | Out-String
    return $output, $LASTEXITCODE
}

function Main {
    # Advanced function so $PSCmdlet (and thus ShouldProcess) resolves inside Main.
    [CmdletBinding(SupportsShouldProcess)]
    param()

    try {
        Write-Host "[*] Checking Credential Manager for stale credentials..." -ForegroundColor Cyan

        # Generic (application-created) credential types - shared with detect.ps1.
        $genericTypePatterns = @('LegacyGeneric:', 'LegacyDiscardable:')

        # Credentials Windows creates and regenerates by design - never delete these.
        $byDesignPatterns = @('virtualapp/didlogical', '_MSLITE_', 'MicrosoftAccount', 'WindowsLive')

        $remediationActions = @()

        # Out-String coalesces the line-per-object native output into a single
        # newline-separated string so the Target: regex matches each credential line
        # individually (an array passed to [regex]::Matches would be space-joined,
        # collapsing all entries).
        $listResult = Invoke-CmdKey /list
        $credList = [string]$listResult[0]
        $listExitCode = [int]$listResult[1]

        if ($listExitCode -eq 0) {
            # Parse credential list
            $targetPattern = "Target:\s+(.+)"
            $credentialMatches = [regex]::Matches($credList, $targetPattern)

            foreach ($match in $credentialMatches) {
                $target = $match.Groups[1].Value.Trim()

                # Skip by-design credentials
                $isByDesign = $false
                foreach ($byDesign in $byDesignPatterns) {
                    if ($target -match $byDesign) {
                        $isByDesign = $true
                        break
                    }
                }
                if ($isByDesign) { continue }

                # Remove generic (app-created) credentials - same set detect.ps1 flags
                foreach ($typePattern in $genericTypePatterns) {
                    if ($target -like "$typePattern*") {
                        if ($PSCmdlet.ShouldProcess($target, "Delete stale credential")) {
                            $deleteResult = Invoke-CmdKey "/delete:$target"
                            if ([int]$deleteResult[1] -eq 0) {
                                $remediationActions += "Removed stale credential: $target"
                            }
                            else {
                                Write-Host "[!] Could not remove credential: $target" -ForegroundColor Yellow
                            }
                        }
                        break
                    }
                }
            }
        }
        else {
            Write-Host "[!] cmdkey /list failed with exit code $listExitCode" -ForegroundColor Yellow
        }

        if ($remediationActions.Count -gt 0) {
            Write-Host "[+] Credential Manager remediation completed:" -ForegroundColor Green
            foreach ($action in $remediationActions) {
                Write-Host "    - $action"
            }
        }
        else {
            Write-Host "[+] Already clean: no stale credentials found to remove" -ForegroundColor Green
        }

        return 0
    }
    catch {
        Write-Host "[-] Error during Credential Manager remediation: $($_.Exception.Message)" -ForegroundColor Red
        return 1
    }
}

# Execute only when run as a script; dot-sourcing (Pester tests, module builds) skips execution.
if ($MyInvocation.InvocationName -ne '.') { exit (Main) }
